
@new_url = https://XXXX.cpq.cloud.sap
@username = 
@password =

###  Password Grant API Authentication
# @name login
POST {{new_url}}/oauth2/token
Content-Type: application/json;charset=UTF-8

grant_type=password&username={{username}}&password={{password}}&scope=configurations_admin

@accessToken = {{login.response.body.access_token}}


###  To Create a New quote and copy the quote id from response
POST {{new_url}}/api/v1/quotes
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
   "quoteNumber": "3211113213213213",
    "OpportunityId": "985406-3454",
    "OpportunityName": "TestSAP"
}

###
GET {{new_url}}/api/v1/quotes?$top=1000&$skip=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 
GET {{new_url}}/api/v1/quotes?$filter=datecreated eq '2024-04-30'
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes?$filter=(datecreated ge '2024-04-30' and datecreated le '2024-04-30')
Authorization: Bearer {{accessToken}}
Content-Type: application/json  

###
GET {{new_url}}/api/v1/quotes?$filter=QuoteId eq '1340'
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/3658
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/3658/items?&$skip=0&$top=1000
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/3658/items?$expand=SelectedAttributes&$expand=PricingConditions&$expand=ExternalConfigurations
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/1610/items/$count
Authorization: Bearer {{accessToken}}
Content-Type: application/json
  
###
GET {{new_url}}/api/v1/quotes/1610/productTypes
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/1610/conditions
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/1610/revisions
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/1610/comments
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/1610/actions
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/1610/involvedParties
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/1610/documents
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/1610/approvals
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/1610/approvals/responsibilities
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/1610/attachments
Authorization: Bearer {{accessToken}}
Content-Type: application/json  
