
@new_url = https://XXXX.cpq.cloud.sap
@username = 
@password =

###  Password Grant API Authentication
# @name login
POST {{new_url}}/oauth2/token
Content-Type: application/json;charset=UTF-8

grant_type=password&username={{username}}&password={{password}}&scope=configurations_admin

@accessToken = {{login.response.body.access_token}}


###  To Create a New quote and copy the quote id from response
POST {{new_url}}/api/v1/quotes
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
   "quoteNumber": "3211113213213213",
    "OpportunityId": "985406-3454",
    "OpportunityName": "TestSAP"
}

###
GET {{new_url}}/api/v1/quotes?$top=1000&$skip=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 
GET {{new_url}}/api/v1/quotes?$filter=datecreated eq '2024-04-30'
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes?$filter=(datecreated ge '2024-04-30' and datecreated le '2024-04-30')
Authorization: Bearer {{accessToken}}
Content-Type: application/json  

###
GET {{new_url}}/api/v1/quotes?$filter=QuoteId eq '1340'
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### update the quote Id
@quoteid = 1610

###
GET {{new_url}}/api/v1/quotes/{{quoteid}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/{{quoteid}}/items?&$skip=0&$top=1000
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/{{quoteid}}/items/$count
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/{{quoteid}}/items?$expand=SelectedAttributes&$expand=PricingConditions&$expand=ExternalConfigurations
Authorization: Bearer {{accessToken}}
Content-Type: application/json
  
###
GET {{new_url}}/api/v1/quotes/{{quoteid}}/productTypes
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/{{quoteid}}/conditions
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/{{quoteid}}/revisions
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/{{quoteid}}/comments
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/{{quoteid}}/actions
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/{{quoteid}}/involvedParties
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/{{quoteid}}/documents
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/{{quoteid}}/approvals
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/{{quoteid}}/approvals/responsibilities
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{new_url}}/api/v1/quotes/{{quoteid}}/attachments
Authorization: Bearer {{accessToken}}
Content-Type: application/json  

###
GET {{new_url}}/api/v1/quotes/{{quoteid}}/quoteTables/<your quote table>/rows
Authorization: Bearer {{accessToken}}
Content-Type: application/json  


##################  Updating the Quote items and quote Headers #########################

###
PATCH {{new_url}}/api/v1/quotes/{{quoteid}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "Project Name" : "vvvv"
}

###
PATCH {{new_url}}/api/v1/quotes/{{quoteid}}/items/11438
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "DiscountPercent": "1.0000"
}

###
POST {{new_url}}/api/v1/quotes/{{quoteid}}/items
Authorization: Bearer {{accessToken}}
Content-Type: application/json

[
  {
    "PartNumber": "sp001",
    "Quantity": 1,
    "discount": 5.0
  }
]
